---
- hosts: all

  vars:
    libfprint_ver: "1.94.2"

  tasks:
  - import_tasks: tasks/wifi.yaml
    tags: ['wifi']

  - import_tasks: tasks/fprint.yaml
    tags: ['fprint']

  handlers:
  - name: Reboot
    reboot:
    # It appears reboot only works for remote connection,
    # not sure how to make it works for local yet
    when: ansible_connection != 'local'

