---

- name: "Install dependencies"
  apt:
    name:
    - build-essential
    - python3-pip
    - ninja-build
    - gtk-doc-tools
    - libglib2.0-dev
    - libgusb-dev
    - libgirepository1.0-dev
  become: true

- name: "Install meson"
  pip:
    name:
    - meson
    extra_args: --user

- name: "Build fprintd"
  block:
  - name: "Create temp dir"
    tempfile:
       state: directory
    register: tempdir

  - name: "Download Source Code"
    unarchive:
      src: "https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.94.2/libfprint-v1.94.2.tar.gz"
      dest: "{{ tempdir.path }}"

  - name: "Meson Configure libfprint"
    command:
      cmd: meson build -Ddrivers=goodixmoc
      chdir: "{{ tempdir.path }}/libfprint-v1.94.2"

  - name: "Meson Build libfprint"
    command:
      cmd: meson compile
      chdir: "{{ tempdir.path }}/libfprint-v1.94.2/build"

  - name: "Meson Install libfprint"
    command:
      cmd: meson install
      chdir: "{{ tempdir.path }}/libfprint-v1.94.2/build"

  always:
  - name: "Remove temp dir"
    file:
      path: "{{ tempdir.path }}"
      state: absent

