---
# basically following guide here
# ref: https://github.com/iberianpig/fusuma
- name: "Install dependencies"
  apt:
    name:
    - libinput-tools
    - ruby
    - xdotool
  become: true

- name: Install fusuma Ruby Gem
  community.general.gem:
    name: fusuma
    state: present
    user_install: false
  become: true

- name: Add user to input group
  ansible.builtin.user:
    name: "{{ user.username }}"
    groups: input
    append: true
  become: true
  loop: "{{ fusuma.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: Create fusuma config folder
  ansible.builtin.file:
    path: "~{{ user.username }}/.config/fusuma"
    state: directory
  become: true
  become_user: '{{ user.username }}'
  when: "user.enable_config | bool"
  loop: "{{ fusuma.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: Write fusuma config file
  ansible.builtin.copy:
    dest: "~{{ user.username }}/.config/fusuma/config.yml"
    content: "{{ user.config | default(fusuma.default_config) | to_nice_yaml  }}"
  become: true
  become_user: '{{ user.username }}'
  when: "user.enable_config | bool"
  loop: "{{ fusuma.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: write fusuma.desktop autostart for users
  template:
    src: fusuma.desktop.jinja2
    dest: '~{{ user.username }}/.config/autostart/fusuma.desktop'
  become: yes
  become_user: '{{ user.username }}'
  when: "user.autostart | default(fusuma.autostart) | bool"
  loop: "{{ fusuma.users }}"
  loop_control:
    loop_var: user
    label: '{{ user.username }}'

- name: remove fusuma.desktop autostart for users
  file:
    path: '~{{ user.username }}/.config/autostart/fusuma.desktop'
    state: absent
  become: yes
  become_user: '{{ user.username }}'
  when: "not (user.autostart | default(fusuma.autostart) | bool)"
  loop: "{{ fusuma.users }}"
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
